### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by MISTERNEGATIVE21** [daucu/daucu#5]
After installing daucu as root , while navigating to /ui its showing nothing
![image](https://github.com/daucu/daucu/assets/51168229/419bd83b-8343-4659-808c-d05616d10793)
![image](https://github.com/daucu/daucu/assets/51168229/7cd0e310-968c-463e-8df9-998c307ad546)
version in daucu differed just now

**Comment by daucu** [comment]
Hi sir sorry for issue i am fixing this issue

**Comment by daucu** [comment]
harshaweb

**Comment by daucu** [comment]
Reinstall and try to access on port 3000 it will work
